-- Insert into user table
INSERT INTO USERS_ (USERNAME, PASSWORD, NAME, CREATED_BY, CREATED_DATETIME) VALUES ('john@example.com', 'password1', 'John Tan', 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO USERS_ (USERNAME, PASSWORD, NAME, CREATED_BY, CREATED_DATETIME) VALUES ('mark@example.com', 'password2', 'Mark Lee', 'SYSTEM', CURRENT_TIMESTAMP);

-- Insert into role table
INSERT INTO ROLE (ROLE_NAME, ROLE_DESCRIPTION) VALUES ('MANAGER', 'ROLE WITH ADDITIONAL RIGHTS');
INSERT INTO ROLE (ROLE_NAME, ROLE_DESCRIPTION) VALUES ('USER', 'DEFAULT ROLE');

-- Insert into function table
INSERT INTO FUNCTION_(FUNCTION_NAME, FUNCTION_CODE, FUNCTION_DESCRIPTION) VALUES ('LANDING PAGE', 'V01', 'VIEW LANDING PAGE');
INSERT INTO FUNCTION_(FUNCTION_NAME, FUNCTION_CODE, FUNCTION_DESCRIPTION) VALUES ('USER DETAILS', 'VL01', 'VIEW USER DETAILS');
INSERT INTO FUNCTION_(FUNCTION_NAME, FUNCTION_CODE, FUNCTION_DESCRIPTION) VALUES ('ALL ACCOUNTS', 'VL02', 'VIEW ALL ACCOUNTS');

-- Insert into user_role table
INSERT INTO USER_ROLE (USER_ID, ROLE_ID, EFFECTIVE_DATE) VALUES (1, 1, CURRENT_TIMESTAMP);
INSERT INTO USER_ROLE (USER_ID, ROLE_ID, EFFECTIVE_DATE) VALUES (2, 2, CURRENT_TIMESTAMP);

-- Insert into role_function table
INSERT INTO ROLE_FUNCTION(ROLE_ID, FUNCTION_ID) VALUES (1, 1);
INSERT INTO ROLE_FUNCTION(ROLE_ID, FUNCTION_ID) VALUES (1, 2);
INSERT INTO ROLE_FUNCTION(ROLE_ID, FUNCTION_ID) VALUES (1, 3);
INSERT INTO ROLE_FUNCTION(ROLE_ID, FUNCTION_ID) VALUES (2, 1);
INSERT INTO ROLE_FUNCTION(ROLE_ID, FUNCTION_ID) VALUES (2, 2);
